### ISSUE TITLE
您好，项目在本地yarn install以后报错，请问怎么解决？

### ISSUE THREAD

**Issue by zhuxiaoweb** [yanbowe/taro-vue3-pinia#3]
Compiled with problems:X

ERROR in ./src/app.config.ts 1:0-20

Module not found: Error: Can't resolve './app.boot' in '/Users/zhuxiao/Documents/workspace/aie-wx/src'

ERROR in ./src/app.config.ts 1:0-20
Module not found: Error: Can't resolve './app.boot' in '/Users/zhuxiao/Documents/workspace/aie-wx/src'
resolve './app.boot' in '/Users/zhuxiao/Documents/workspace/aie-wx/src'
  using description file: /Users/zhuxiao/Documents/workspace/aie-wx/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /Users/zhuxiao/Documents/workspace/aie-wx/package.json (relative path: ./src/app.boot)
      no extension

**Comment by yanbowe** [comment]
项目使用的是pnpm,使用pnpm install

**Comment by zhuxiaoweb** [comment]
> 项目使用的是pnpm,使用pnpm install

您好，我用pnpm和cnpm、yarn都试过了报的还是同一个错

**Comment by yanbowe** [comment]
> > 项目使用的是pnpm,使用pnpm install
> 
> 您好，我用pnpm和cnpm、yarn都试过了报的还是同一个错

node和pnpm是什么版本的

**Comment by zhuxiaoweb** [comment]
> node
node v18.12.1
pnpm 7.17.0

**Comment by zhuxiaoweb** [comment]
OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.12.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn

**Comment by zhuxiaoweb** [comment]
> > > 项目使用的是pnpm,使用pnpm install
> > 
> > 
> > 您好，我用pnpm和cnpm、yarn都试过了报的还是同一个错
> 
> node和pnpm是什么版本的

兄弟你本地重新install可以运行h5吗？

**Comment by yanbowe** [comment]
> > > > 项目使用的是pnpm,使用pnpm install
> > > 
> > > 
> > > 您好，我用pnpm和cnpm、yarn都试过了报的还是同一个错
> > 
> > 
> > node和pnpm是什么版本的
> 
> 兄弟你本地重新install可以运行h5吗？

是有问题，我这边排查一下

**Comment by zhuxiaoweb** [comment]
> > > > > 项目使用的是pnpm,使用pnpm install
> > > > 
> > > > 
> > > > 您好，我用pnpm和cnpm、yarn都试过了报的还是同一个错
> > > 
> > > 
> > > node和pnpm是什么版本的
> > 
> > 
> > 兄弟你本地重新install可以运行h5吗？
> 
> 是有问题，我这边排查一下

好的 谢谢！我也在看 有进展即时沟通。

**Comment by zhuxiaoweb** [comment]
好像不止我们两个遇到这个问题了

**Comment by yanbowe** [comment]
> 好像不止我们两个遇到这个问题了

估计是taro的问题，我在另外的[项目](https://github.com/MellowCo/unocss-preset-weapp/issues/16)里遇到了同样的问题

**Comment by zhuxiaoweb** [comment]
> taro

taro真给力 我明天要给cto演示技术方案。。。

**Comment by yanbowe** [comment]
> > taro
> 
> taro真给力 我明天要给cto演示技术方案。。。

哈哈，那就很危险了

**Comment by zhuxiaoweb** [comment]
> 

先演示小程序吧

**Comment by yanbowe** [comment]
> > 
> 
> 先演示小程序吧

unocss引入也会出现问题，可能需要先放弃使用unocss

**Comment by zhuxiaoweb** [comment]
> > > 
> > 
> > 
> > 先演示小程序吧
> 
> unocss引入也会出现问题，可能需要先放弃使用unocss

如果打包环境也有问题估计会影响很多生产项目，那就有点严重了

**Comment by yanbowe** [comment]
taro相关[issues](https://github.com/NervJS/taro/issues/12869)
