### ISSUE TITLE
安卓机的顶部导航栏navbar显示位置上移

### ISSUE THREAD

**Issue by LiaoKD** [yanbowe/taro-vue3-pinia#4]
![WechatIMG64](https://github.com/yanbowe/taro-vue3-pinia/assets/131249161/48380112-852a-4267-92e1-d8134da5d9bc)
![WechatIMG63](https://github.com/yanbowe/taro-vue3-pinia/assets/131249161/37a9dffd-6ebf-4693-a494-373cb14cb183)
头部导航栏在iPhone上显示正常，安卓机的适配有问题。安卓机型号分别是红米k40和华为nova8.

**Comment by yanbowe** [comment]
考虑到是 nut-navbar顶部安全区属性失效问题，已修改为手动适配
