### ISSUE TITLE
自定义组件引入pinia时报错

### ISSUE THREAD

**Issue by pwshijiezuiniu** [yanbowe/taro-vue3-pinia#6]
自定义组件引入pinia时报错
import { defineComponent } from 'vue'
import { useAppStore } from '@/store/modules/app'

const appStore = useAppStore()
const TableIcon = computed(() => appStore.getTableIcon)

export default defineComponent({
	name: 'Table',
	setup(){
	 
	}
})

放入setup后报错消失

**Comment by yanbowe** [comment]
可以参考[basic-layout](https://github.com/yanbowe/taro-vue3-pinia/tree/main/src/components/basic-layout)组件，基础类问题建议去查文档更好
